import { useState } from 'react'
import { BookOpen, ChevronDown, ExternalLink, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Card, Eyebrow } from '../components/ui'
import { EVIDENCE } from '../lib/evidence'

export default function Methodology() {
  const [technical, setTechnical] = useState(false)
  return (
    <div className="space-y-5">
      <div className="space-y-2"><Eyebrow>Info & transparansi</Eyebrow><h1 className="text-balance text-[30px] font-extrabold leading-tight text-[#172b3a]">Kenapa Bercabang tidak bisa menjawab dengan pasti?</h1><p className="text-pretty text-[15px] leading-7 text-[#617383]">Karena hidup punya banyak variabel yang tidak bisa diamati dengan rapi. Kami memilih menunjukkan batas-batasnya.</p></div>
      <Card className="space-y-4 p-5"><div className="flex items-start gap-3"><BookOpen className="mt-0.5 shrink-0 text-[#087f8c]" size={21} /><div><h2 className="font-extrabold text-[#314b56]">Cara Bercabang bekerja</h2><p className="mt-2 text-sm leading-6 text-[#71868a]">Kami membandingkan pilihan dengan pola dari kelompok yang mirip, lalu menunjukkan rentang kemungkinan. Hasilnya bukan ramalan dan bukan instruksi.</p></div></div><div className="space-y-2 text-sm leading-6 text-[#536c72]"><p><b>1. Isi konteks.</b> Hanya data yang membantu memahami pilihanmu.</p><p><b>2. Tulis ekspektasi.</b> Kami membuatmu melihat jawaban sendiri sebelum data.</p><p><b>3. Lihat rentang.</b> Kami menampilkan pola, risiko, dan hal yang belum diketahui.</p></div></Card>
      <Card className="space-y-3 p-5"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 shrink-0 text-[#c9663c]" size={21} /><div><h2 className="font-extrabold text-[#314b56]">Yang tidak boleh Bercabang lakukan</h2><p className="mt-2 text-sm leading-6 text-[#71868a]">Kami tidak mendiagnosis, tidak memprediksi orang lain, dan tidak memberi perintah “melakukan” atau “tidak melakukan”.</p></div></div></Card>
      <Card className="overflow-hidden p-5"><button onClick={() => setTechnical((current) => !current)} className="flex w-full items-center justify-between text-left"><div><Eyebrow>Untuk yang ingin lebih dalam</Eyebrow><h2 className="mt-1 text-lg font-extrabold text-[#314b56]">Metode, batasan, dan sumber</h2></div><ChevronDown size={19} className={`text-[#087f8c] transition ${technical ? 'rotate-180' : ''}`} /></button>{technical && <div className="mt-5 space-y-5"><div className="rounded-2xl bg-[#172b3a] p-4 text-sm leading-6 text-white/80"><p className="font-extrabold text-white">Inti metode</p><p>Kami memakai kerangka target trial emulation, pencocokan kelompok, dan rentang ketidakpastian. Hasil pada kelompok bukan perkiraan pasti untuk satu orang.</p><p className="mt-2">Data utama: IFLS 2014/15. Bercabang tidak mengklaim data real-time.</p></div><div><p className="text-sm font-extrabold text-[#314b56]">Sumber yang menjadi dasar</p><div className="mt-2 space-y-2">{EVIDENCE.map((item) => <div key={item.id} className="rounded-2xl bg-[#f2f8f6] p-4 text-sm leading-6 text-[#617383]"><p className="font-extrabold text-[#314b56]">{item.citation}</p><p className="mt-1">{item.claim}</p><p className="mt-1 text-xs text-[#8aa0a0]">Transferabilitas ke Indonesia: {item.transferabilityToID}</p></div>)}</div></div></div>}</Card>
      <Card className="space-y-3 p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#16705a]" size={21} /><div><h2 className="font-extrabold text-[#314b56]">Privasi dalam bahasa sederhana</h2><p className="mt-2 text-sm leading-6 text-[#71868a]">Profil dan riwayat disimpan di perangkat. Tidak ada iklan, tidak ada akun sosial, dan kamu bisa menghapus semuanya dengan satu tombol.</p></div></div><a href="https://www.rand.org/well-being/social-and-behavioral-policy/data/FLS/IFLS.html" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#087f8c]">Baca sumber IFLS <ExternalLink size={15} /></a></Card>
    </div>
  )
}
